language: node_js

node_js:
  - 16

cache:
  yarn: true
  directories:
    - node_modules

stages:
 - test

jobs:
  include:
    - name: Lint
      stage: test
      script: yarn lint
    - name: Test
      stage: test
      script: yarn test --coverage
    - name: "Pod install check"
      stage: test
      os: osx
      language: objective-c
      osx_image: xcode13.3
      env:
        - JOB_NAME=IOS
      before_install:
        - npm install -g yarn
        - yarn --frozen-lockfile
      script:
        - cd ios && pod install --deployment
      cache:
        cocoapods: true
        yarn: true
        directories:
          - node_modules
      podfile: ios/Podfile
