language: node_js

node_js:
  - 16.18.1

cache:
  yarn: true
  directories:
    - node_modules

stages:
 - test

jobs:
  include:
    - name: Lint
      stage: test
      script: yarn lint
    - name: Test
      stage: test
      script: yarn test --coverage
