language: node_js

node_js:
  - 16

cache:
  yarn: true
  directories:
    - node_modules

stages:
 - test

jobs:
  include:
    - name: Lint
      stage: test
      script: yarn lint
    - name: Test
      stage: test
      script: yarn test --coverage
    - name: "Pod install check"
      stage: test
      os: osx
      language: objective-c
      osx_image: xcode13.3
      env:
        - JOB_NAME=IOS
      script:
        - yes Y | gem uninstall cocoapods -aIx
        - gem install cocoapods -v 1.10.1
        - npm install -g yarn
        - yarn --frozen-lockfile
        - cd ios && pod install --deployment
