import RNIAP from 'react-native-iap'

export const mockRNIAP: jest.Mocked<typeof RNIAP> = {
  clearTransactionIOS: jest.fn(),
  requestSubscription: jest.fn(),
  isIosStorekit2: jest.fn(),
  setup: jest.fn(),
  initConnection: jest.fn(),
  endConnection: jest.fn(),
  flushFailedPurchasesCachedAsPendingAndroid: jest.fn(),
  getProducts: jest.fn(),
  getSubscriptions: jest.fn(),
  getPurchaseHistory: jest.fn(),
  getAvailablePurchases: jest.fn(),
  requestPurchase: jest.fn(),
  finishTransaction: jest.fn(),
  deepLinkToSubscriptions: jest.fn(),
  purchaseUpdatedListener: jest.fn(),
  purchaseErrorListener: jest.fn(),
  promotedProductListener: jest.fn(),
  transactionListener: jest.fn(),
  useIAP: jest.fn(),
  useIAPContext: jest.fn(),
  withIAPContext: jest.fn(),
  validateReceiptAmazon: jest.fn(),
  verifyLicense: jest.fn(),
  deepLinkToSubscriptionsAmazon: jest.fn(),
  getInstallSourceAndroid: jest.fn(),
  deepLinkToSubscriptionsAndroid: jest.fn(),
  validateReceiptAndroid: jest.fn(),
  acknowledgePurchaseAndroid: jest.fn(),
  isFeatureSupported: jest.fn(),
  getPendingPurchasesIOS: jest.fn(),
  getReceiptIOS: jest.fn(),
  presentCodeRedemptionSheetIOS: jest.fn(),
  getPromotedProductIOS: jest.fn(),
  buyPromotedProductIOS: jest.fn(),
  validateReceiptIos: jest.fn(),
  clearProductsIOS: jest.fn(),
  deepLinkToSubscriptionsIos: jest.fn(),
} as unknown as jest.Mocked<typeof RNIAP>
