require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CozyReactNative' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'react-native-gzip', :path => '../node_modules/@fengweichong/react-native-gzip'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-document-scanner-android', :path => '../node_modules/react-native-documentscanner-android'

  pod 'react-native-document-scanner', :path => '../node_modules/react-native-document-scanner'

  target 'CozyReactNativeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.87.0' , 'Flipper-Folly' => '2.5.3' , 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'CozyReactNative-tvOS' do
  # Pods for CozyReactNative-tvOS

  target 'CozyReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
